[build]
  base = ""  
  command = "npm run build"  
  publish = "src"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  included_files = ["src/blog/entries/**"]
  node_bundler = "esbuild"
